### ISSUE TITLE
Tag master for Symfony 7

### ISSUE THREAD

**Issue by ping-localhost** [sfmok/request-input-bundle#19]
@sfmok could you please tag/release the changes in master? Would love to use this bundle in Symfony 7, since the FOSRestBundle `body_converter` within cannot be used anymore (and this bundle fills that gap easily).

**Comment by ping-localhost** [comment]
@sfmok can you please tag master?

**Comment by sfmok** [comment]
> @sfmok can you please tag master?

Thanks for your comment. Soon, I will release a new version that supports symfony 7

**Comment by sfmok** [comment]
@ping-localhost A new version (1.2.6) has been released that supports Symfony 7.
